using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace AutoDI.SourceGenerator
{
    internal static class RegistrationEmitter
    {
        public static void Emit(
            SourceProductionContext ctx,
            ImmutableArray<RegistrationModel> models)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine();
            sb.AppendLine("namespace AutoDI");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class AutoDIServiceCollectionExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoRegisteredServices(");
            sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            sb.AppendLine("        {");

            foreach (var model in models)
            {
                foreach (var line in GetRegistrationLines(model))
                {
                    sb.Append("            ");
                    sb.AppendLine(line);
                }
            }

            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource(
                "AutoDI.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static ImmutableArray<string> GetRegistrationLines(RegistrationModel model)
        {
            var lines = ImmutableArray.CreateBuilder<string>();

            string methodName;
            switch (model.Lifetime)
            {
                case ServiceLifetime.Scoped: methodName = "AddScoped"; break;
                case ServiceLifetime.Singleton: methodName = "AddSingleton"; break;
                case ServiceLifetime.Transient: methodName = "AddTransient"; break;
                default: return lines.ToImmutable();
            }

            if (model.InterfaceFQNs.IsEmpty)
            {
                lines.Add($"services.{methodName}<{model.ImplementationFQN}>();");
            }
            else
            {
                foreach (var iface in model.InterfaceFQNs)
                    lines.Add($"services.{methodName}<{iface}, {model.ImplementationFQN}>();");
            }

            return lines.ToImmutable();
        }
    }
}
