//HintName: AutoDI.g.cs
// <auto-generated/>

using Microsoft.Extensions.DependencyInjection;
namespace AutoDI
{
    public static partial class AutoDIServiceCollectionExtensions
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoRegisteredServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            services.AddScoped(typeof(global::TestApp.IRepo<>), typeof(global::TestApp.Repo<>));
            return services;
        }
    }
}
