//HintName: AutoDI.g.cs
// <auto-generated/>

namespace AutoDI
{
    public static partial class AutoDIServiceCollectionExtensions
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoRegisteredServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            services.AddSingleton<global::TestApp.IFooService, global::TestApp.FooService>();
            return services;
        }
    }
}
