//HintName: AutoDI.g.cs
// <auto-generated/>

using Microsoft.Extensions.DependencyInjection;
namespace AutoDI
{
    public static partial class AutoDIServiceCollectionExtensions
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoRegisteredServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            services.AddSingleton<global::TestApp.IFoo, global::TestApp.FooBarService>();
            services.AddSingleton<global::TestApp.IBar, global::TestApp.FooBarService>();
            return services;
        }
    }
}
